Issue 782 - NoSuchMethodError when excluding a WebSocket channel URL from context
 - Changed the ContextExcludePanel class to:
    - Restore (and deprecate) the older method #getPanelName(Context) which is used by (older) "WebSocket" add-on versions;
    - Set the JavaDoc @since tag (version 2.2.0) to the newer method #getPanelName(int), added JavaDoc and renamed the parameter to "contextIndex".
 - Changed the ContextIncludePanel class to:
    - Restore (and deprecate) the older method #getPanelName(Context) just in case it's also being used by an (older) add-on;
    - Set the JavaDoc @since tag (version 2.2.0) to the newer method #getPanelName(int), added JavaDoc and renamed the parameter to "contextIndex".

git-svn-id: https://zaproxy.googlecode.com/svn/trunk@3519 0fcac13d-f916-6cb6-7431-acacdca54389